version: 2
updates:
  - package-ecosystem: "openai"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "tiktoken"
    directory: "/"
    schedule:
      interval: "daily"
